### ISSUE TITLE
DELETE all your MAC Addresses

### ISSUE THREAD

**Issue by chrisrock1984** [the-automation-gym/Loxone-Templates#1]
Please be aware, that offering your MAC address to the public, can have an impact to your miniserver!
Your MAC address is visible in an youtube video and  in the python code!!

**Comment by the-automation-gym** [comment]
Hi Chris, thank you for your concern I know that very well myself. 

This Miniserver is used for testing and educational purposes only, I have another few for my own installations that I'd never publicly share.
